"""Teaching content for the Voice Studio. All practice texts here are original,
written to exercise the measured habits; only 2-6 word fragments of the reel
appear (as evidence labels). Built into voice-studio.html by build.py."""

TECHNIQUES = [
  # TONE
  {"pillar": "tone", "mode": "perf", "name": "Wounded dignity",
   "what": "The narrator is a man of total self-belief describing his own humiliation. He never sounds angry. He sounds politely, deeply hurt, as if writing to his bank manager.",
   "evidence": "No shouting anywhere in 106 s. His loudest words are pivots (if, completely, security), not insults.",
   "drill": "Read a shopping list as a formal complaint to the supermarket. Polite, hurt, utterly serious."},
  {"pillar": "tone", "mode": "perf", "name": "High setup, low punch",
   "what": "The words that lead up to the joke climb high in his voice. The joke word itself drops to the floor and goes flat.",
   "evidence": "'I can only describe as solid' rises to +7.6 semitones on the build, then 'solid' falls to −14.",
   "drill": "Say 'It was, without question, a disaster' five times: the first five words climb, 'disaster' drops."},
  {"pillar": "tone", "mode": "both", "name": "A baritone that moves",
   "what": "His home pitch is low and resonant, but he travels a long way from it. The range is the tone. A flat low voice sounds bored; his sounds amused.",
   "evidence": "Stage range: 21.5 semitones (5th to 95th percentile). Many speakers stay under 12.",
   "drill": "Sirens: glide from your lowest comfortable note to your highest on 'ooo', 5 times, then say a sentence using the top and bottom."},
  # PACE
  {"pillar": "pace", "mode": "perf", "name": "Sprint and stop",
   "what": "Inside a phrase he is very fast. Then he stops completely. The average pace hides this: it's the contrast that makes him sound in control.",
   "evidence": "248 wpm inside phrases (5.6 syllables/s), but 179 wpm overall because 28% of the time is silence.",
   "drill": "Count 1 to 10 as fast and crisp as you can, stop dead for two seconds, repeat. Then do it with a sentence."},
  {"pillar": "pace", "mode": "perf", "name": "Hurry the logistics, slow the payoff",
   "what": "The boring parts of the story (going round the back, finding a window) get rushed. The words that matter get slowed and stretched.",
   "evidence": "10-second windows swing from 96 to 228 wpm. The slow windows hold the punchlines.",
   "drill": "Tell how you got to work today. Rush the travel, slow right down for the one thing that went wrong."},
  {"pillar": "pace", "mode": "both", "name": "A hierarchy of silences",
   "what": "Not all pauses are the same. Short ones (under half a second) separate list items. A one-second beat comes before a new idea. Two to four seconds comes after a punchline, for the laugh.",
   "evidence": "21 pauses ≥ 0.25 s: 11 short, 6 medium, 4 long (2.6 to 4.2 s), and every long one comes right after a joke.",
   "drill": "Read any paragraph marking ‖ ‖‖ ‖‖‖ in pencil first, then perform it obeying the marks exactly."},
  # FLUENCY
  {"pillar": "fluency", "mode": "both", "name": "Restart on a marker, never on 'um'",
   "what": "After every pause he comes back in with a clean discourse marker: Now, / But / And / Obviously, / Undeterred,. The pause is silent; the restart is a word with a job.",
   "evidence": "Zero fillers in the reel. Every sentence after a long pause opens with a marker.",
   "drill": "Talk for 60 s about your morning. Every time you'd say 'um', go silent instead, then restart with 'Now,' or 'But'."},
  {"pillar": "fluency", "mode": "both", "name": "Stretch instead of stall",
   "what": "When he needs a moment, he lengthens an important word instead of filling the gap. It buys thinking time and adds meaning.",
   "evidence": "His longest words are emphasis words: 'definitely' 0.74 s, 'backfired' 0.58 s, 'enormity' 0.52 s.",
   "drill": "Say 'It was absolutely enormous' stretching a different word each time. Notice which stretch sounds most like him."},
  {"pillar": "fluency", "mode": "both", "name": "Breath for the long run",
   "what": "Most runs are short (about 2 s), but he can hold a 10-second run without a breath when the story needs momentum.",
   "evidence": "Median run 1.9 s; longest 10.3 s (about 42 words) in one breath.",
   "drill": "Breath ladder: one breath for 'one', then 'one two', up to ten. Keep the last word as strong as the first."},
  # VOCABULARY
  {"pillar": "vocab", "mode": "perf", "name": "Register collision",
   "what": "He places a formal, Latinate phrase right next to a blunt everyday word. The formality makes the bluntness funny, and the bluntness makes the formality funny.",
   "evidence": "'Undeterred', 'on this occasion', 'in question', 'the sheer enormity' all sit beside crude or slapstick details.",
   "drill": "Describe spilling coffee on yourself using three phrases from the Lexicon's mock-formal group."},
  {"pillar": "vocab", "mode": "perf", "name": "Precise vagueness",
   "what": "He refuses to name the awful thing directly and then names it anyway: 'something I can only describe as…'. The delay is the joke.",
   "evidence": "'…I can only describe as | solid', with a 4.1 s laugh after it.",
   "drill": "Five times: 'a smell I can only describe as ___'. Make the last word short and blunt."},
  {"pillar": "vocab", "mode": "nat", "name": "Warm intensifiers",
   "what": "In conversation he reaches for a small set of warm, slightly grand words to praise things, and soft hedges to make opinions modest.",
   "evidence": "__NAT_VOCAB_EVIDENCE__",
   "drill": "Describe a meal you loved using two intensifiers and one hedge, e.g. 'genuinely extraordinary, sort of'."},
  # SYNTAX
  {"pillar": "syntax", "mode": "perf", "name": "Drop into the scene",
   "what": "Start mid-action, then switch to the present tense for the sudden event. It makes the listener feel it's happening now.",
   "evidence": "Opens with 'So there I was', then the event arrives in the present tense ('pulls up', 'climbs').",
   "drill": "Tell any small incident starting 'So there I was, ___ing, when ___ (present tense)'."},
  {"pillar": "syntax", "mode": "perf", "name": "The fork ending",
   "what": "End with two conditions. If it was innocent, he's gracious. If it wasn't, he's savage. The second half is shorter and harder.",
   "evidence": "The last 15 seconds: a long gracious branch, a held breath on 'if', then a five-word verdict.",
   "drill": "Close a complaint about a late parcel with 'Obviously, if ___, then ___. But if it isn't, ___.'"},
  {"pillar": "syntax", "mode": "nat", "name": "Think out loud, then land",
   "what": "In conversation his sentences grow as he thinks: a start, a self-correction, an aside, then a clear final clause. The repair is part of the style, not a mistake.",
   "evidence": "__NAT_SYNTAX_EVIDENCE__",
   "drill": "Answer 'What's your favourite place?' starting 'I mean, it's… it's sort of…' and finish with one short, clear sentence."},
  # EXPRESSION
  {"pillar": "expr", "mode": "perf", "name": "Never wink",
   "what": "He commits to the narrator's version of events completely. He doesn't laugh at his own jokes and doesn't signal 'this is funny'. The audience does the laughing.",
   "evidence": "On camera: eyes closed in suffering, a scrunched face for disgust, but never a smile during a punchline.",
   "drill": "Tell a ridiculous lie (your cat is a lawyer) with a completely straight, slightly offended face, in the mirror."},
  {"pillar": "expr", "mode": "perf", "name": "Let it land",
   "what": "After the payoff he waits. He doesn't step on the laugh or rush to the next line. The wait tells people it was a joke.",
   "evidence": "Four waits of 2.6 to 4.2 s, all after punchlines.",
   "drill": "Tell a joke to an empty room and hold still for three full seconds after the punchline. It will feel too long. It isn't."},
  {"pillar": "expr", "mode": "nat", "name": "Self-deprecating warmth",
   "what": "He makes himself the butt of the story and praises other people generously. It's charming because he means it.",
   "evidence": "__NAT_EXPR_EVIDENCE__",
   "drill": "Tell a story about a time you were bad at something, ending with a compliment to someone who was good at it."},
]

FRAMES = [
  {"id": "scene", "mode": "perf", "name": "Scene drop",
   "template": "So there I was, [doing something ordinary], when [something sudden happens, present tense].",
   "why": "Starts the story in the middle. The present-tense switch makes it vivid.",
   "examples": ["So there I was, quietly choosing a melon, when a man in a full wetsuit walks up and asks if I'm the manager.",
                "So there I was, halfway through my speech, when the projector decides to show my holiday photos instead."]},
  {"id": "list", "mode": "perf", "name": "List with a turn",
   "template": "[A], [B], [C] | and [something absurd].",
   "why": "Three normal items set a rhythm; the fourth breaks it. Pause before the turn.",
   "examples": ["Doctors, lawyers, two Olympic rowers ‖ and a very confident pigeon.",
                "Candles, champagne, a string quartet ‖ and my uncle, asleep in the fruit bowl."]},
  {"id": "youknowme", "mode": "perf", "name": "Mock-intimate aside",
   "template": "Now, you know me, [name]. I'm not exactly known for [trait]. But on this occasion, [exception].",
   "why": "Drops to a confidential murmur, then admits something embarrassing as if it were noble.",
   "examples": ["Now, you know me, Sandra. I'm not exactly known for panicking. But on this occasion, I hid in the airing cupboard.",
                "Now, you know me, Dev. I'm not known for dancing. But on this occasion, the music simply took over my legs."]},
  {"id": "describe", "mode": "perf", "name": "Precise vagueness",
   "template": "…[something] that I can only describe as | [one blunt word].",
   "why": "Formal build-up, pause, short ugly word. High setup, low punch.",
   "examples": ["The soup had a texture that I can only describe as ‖ upholstery.",
                "He gave me a look that I can only describe as ‖ legal."]},
  {"id": "saythis", "mode": "perf", "name": "Backhanded credit",
   "template": "I'll say this for you, [name]: [genuine compliment]. | [The compliment's dark side].",
   "why": "Mock generosity pitched high, then the sting.",
   "examples": ["I'll say this for you, Martin: your barbecue is very consistent. ‖ Everything is equally black.",
                "I'll say this for you, Priya: you are never late to a meeting. ‖ You simply never arrive."]},
  {"id": "presume", "mode": "perf", "name": "Charitable presumption",
   "template": "All I can presume is that [a generous explanation], because [the damning fact].",
   "why": "Sounds reasonable and forgiving while making the accusation clearer.",
   "examples": ["All I can presume is that the chef was having a difficult week, because the chicken was still, technically, a chicken.",
                "All I can presume is that my invitation was lost in the post, because everyone else seems to have received theirs."]},
  {"id": "fork", "mode": "perf", "name": "The fork ending",
   "template": "Obviously, if [innocent explanation], then [gracious response]. | But if it isn't, | [short verdict].",
   "why": "The gracious half is long and warm; the verdict is short and hard. Pitch high on 'if'.",
   "examples": ["Obviously, if this is some kind of surprise party, then I'm delighted and I'll act surprised. ‖ But if it isn't, ‖ you're all dreadful.",
                "Obviously, if the parcel is simply enjoying a holiday, then I wish it well. ‖ But if it isn't, ‖ I want a refund."]},
  {"id": "tell", "mode": "perf", "name": "Deluded certainty",
   "template": "And they definitely [recognised / admired / wanted] me, | even though they pretended [the opposite]. | You could just tell.",
   "why": "The narrator reads rejection as secret admiration. Stretch 'definitely'.",
   "examples": ["And the cat definitely respected me, even though she pretended to be asleep. You could just tell.",
                "And the interviewers definitely loved me, even though they never called back. You could just tell."]},
  {"id": "undeterred", "mode": "perf", "name": "Undeterred restart",
   "template": "| Undeterred, | I [did something even more ambitious].",
   "why": "After a setback, a formal one-word restart. It resets the story and the room.",
   "examples": ["‖ Undeterred, I tried the back door, which was also, it turned out, a wall.",
                "‖ Undeterred, I signed up for the advanced class."]},
]

PHRASES = [
  # mock-formal connectors (stage)
  {"text": "undeterred", "group": "Mock-formal", "mode": "perf", "meaning": "not discouraged by a setback",
   "use": "restart a story after a failure", "example": "The door was locked. Undeterred, I tried the window."},
  {"text": "on this occasion", "group": "Mock-formal", "mode": "both", "meaning": "this time (formal)",
   "use": "admit an exception to your usual behaviour", "example": "I don't normally cry at adverts, but on this occasion I made an exception."},
  {"text": "the … in question", "group": "Mock-formal", "mode": "perf", "meaning": "the one we're talking about",
   "use": "point at something as if in court", "example": "The sandwich in question had been in my bag since Tuesday."},
  {"text": "all I can presume is that", "group": "Mock-formal", "mode": "perf", "meaning": "my only explanation is",
   "use": "offer a polite but damning explanation", "example": "All I can presume is that the map was drawn by an optimist."},
  {"text": "I can only describe as", "group": "Mock-formal", "mode": "both", "meaning": "the only word for it is",
   "use": "delay a blunt or vivid word for effect", "example": "He sang in a voice I can only describe as ‖ damp."},
  {"text": "the sheer enormity of it", "group": "Mock-formal", "mode": "perf", "meaning": "how huge it was",
   "use": "make something small sound overwhelming", "example": "I stood there, taking in the sheer enormity of the buffet."},
  {"text": "I'll say this for you", "group": "Mock-formal", "mode": "perf", "meaning": "I'll give you credit for this",
   "use": "set up a backhanded compliment", "example": "I'll say this for you, Gary: you commit."},
  {"text": "needless to say", "group": "Mock-formal", "mode": "both", "meaning": "obviously",
   "use": "announce the predictable disaster", "example": "Needless to say, the tent did not survive the night."},
  {"text": "as it transpired", "group": "Mock-formal", "mode": "both", "meaning": "as it turned out",
   "use": "reveal a twist politely", "example": "As it transpired, the 'shortcut' was a river."},
  {"text": "with the greatest respect", "group": "Mock-formal", "mode": "both", "meaning": "I'm about to be rude",
   "use": "open a polite disagreement", "example": "With the greatest respect, that is not a dog. That's a fox."},
  {"text": "I'm not well known for", "group": "Mock-formal", "mode": "perf", "meaning": "I don't usually",
   "use": "confess something as if confiding", "example": "I'm not well known for sprinting, but the goose left me no choice."},
  {"text": "imagine my horror", "group": "Mock-formal", "mode": "perf", "meaning": "you can picture how shocked I was",
   "use": "bring the listener into the disaster", "example": "Imagine my horror when the lid came off the blender."},
  {"text": "taken by surprise", "group": "Mock-formal", "mode": "both", "meaning": "caught unprepared",
   "use": "excuse yourself with dignity", "example": "I'm usually very calm, but I was taken by surprise by the badger."},
  {"text": "I decided I would press on", "group": "Mock-formal", "mode": "perf", "meaning": "I kept going anyway",
   "use": "heroic persistence in a silly situation", "example": "My shoe had gone, but I decided I would press on."},
  # blunt British colloquial
  {"text": "a bit of a faff", "group": "British everyday", "mode": "both", "meaning": "annoying, fiddly, a hassle",
   "use": "understate a chore", "example": "Getting the sofa up the stairs was a bit of a faff."},
  {"text": "knackered", "group": "British everyday", "mode": "both", "meaning": "exhausted",
   "use": "after anything tiring", "example": "Two flights of stairs and I was completely knackered."},
  {"text": "gutted", "group": "British everyday", "mode": "both", "meaning": "deeply disappointed",
   "use": "react to bad news", "example": "They'd sold out of croissants. I was gutted."},
  {"text": "having a go at me", "group": "British everyday", "mode": "both", "meaning": "criticising me",
   "use": "report being told off", "example": "The parking warden started having a go at me."},
  {"text": "not ideal", "group": "British everyday", "mode": "both", "meaning": "bad (strong understatement)",
   "use": "describe a catastrophe calmly", "example": "The boat was sinking, which was not ideal."},
  {"text": "fair play", "group": "British everyday", "mode": "both", "meaning": "credit where due",
   "use": "admire someone's nerve", "example": "He wore shorts in the snow. Fair play to him."},
  {"text": "out of order", "group": "British everyday", "mode": "both", "meaning": "unacceptable behaviour",
   "use": "judge someone's action", "example": "Taking the last biscuit was completely out of order."},
  {"text": "chuffed", "group": "British everyday", "mode": "both", "meaning": "pleased",
   "use": "small proud moments", "example": "I parallel parked first time. Very chuffed."},
]

SCRIPTS = [
  {"id": "gym", "mode": "perf", "title": "Letter to the gym manager",
   "coach": "Wounded dignity. Rush the logistics, land every punch.",
   "text": "Dear Darren, || So there I was, | standing in your reception | in brand-new trainers, | when a young man called Kyle | ^bounces over | and offers me | a ~complimentary~ fitness assessment. ||| "
           "Now, | you know me, Darren. | I'm not *exactly* known | for turning down anything complimentary. || So I said yes. ||| "
           ">> Within four minutes Kyle had me strapped into a machine << | that I can only describe | as a _*medieval* rowing boat. ||| / "
           "I'll ^say this for you, Darren: | the air conditioning is ~superb~. || I know this | because I spent forty minutes | lying face down | ^directly underneath it. ||| / "
           "All I can presume | is that Kyle mistook me | for someone | who had done exercise ~before~. || "
           "Obviously, | if this was all part of some team-building exercise, | then I ^salute you | and I hold no grudge whatsoever. || But if it ^wasn't, || _I'd like my eleven pounds back. |||"},
  {"id": "wedding", "mode": "perf", "title": "Letter to cousin Harriet, re: the wedding",
   "coach": "High setup, low punch. Stretch the self-belief words.",
   "text": "Dearest Harriet, || I am writing about my speech. ||| "
           "As you know, | I had prepared for weeks. | Notes, | jokes, | a ^short poem, || and a dance. ||| "
           "And the guests *definitely* adored me, | even though they ~pretended~ | to look at their phones. | You could just tell. ||| / "
           ">> I'd barely reached the second page when your father stood up << | and announced | that the ^buffet was open. || "
           "Imagine my horror, Harriet. | One hundred and twenty people | moving as a single body | towards a tray of _vol-au-vents. ||| / "
           "Undeterred, || I carried on. | I performed the dance | for the ~waiters~. || They were, | and I say this with the greatest respect, | _not a generous audience. ||| / "
           "Obviously, | if the buffet was simply ready early, | then I forgive everyone completely. || But if it ^wasn't, || I know exactly who to blame. |||"},
  {"id": "hedge", "mode": "perf", "title": "Note to Mr Pemberton next door",
   "coach": "Mock-formal vocabulary against blunt detail. Hold the long pauses.",
   "text": "Mr Pemberton, || I'm writing regarding the hedge. ||| "
           "When I moved in, | it was a ^modest hedge. | Polite. | Waist-high. || It now has | what I can only describe | as _ambitions. ||| / "
           "On Tuesday | it took my post. || On Wednesday | it took my ^bicycle. || This morning, | Mr Pemberton, | it took | the postman. ||| / "
           "I'll say this for you: | it is a *very* healthy hedge. || Needless to say, | the postman ~disagrees~. ||| / "
           "All I can presume | is that you're growing it | for some sort of ^competition. || If so, | I wish you every success. || If not, || _please find your shears. |||"},
  {"id": "council", "mode": "perf", "title": "Appeal to the parking council",
   "coach": "Deluded certainty. Fast through the facts, slow on the verdict.",
   "text": "To whom it may concern, || I am appealing | ticket number four-four-one-seven. ||| "
           ">> I'd like to begin by saying that I am an excellent parker. << || Friends | ^ask me to park | their cars. || Strangers | stop and ~watch~. ||| / "
           "On the day in question, | I left my car | for no more than ^four minutes | to rescue a ~kitten~ | from what I can only describe | as a _very mild situation. ||| / "
           "Your officer | was *definitely* impressed by me, | even though he pretended | to write a ticket. || You could just tell. ||| / "
           "Obviously, | if the ticket was meant as a sort of ^award, | then I accept it | with enormous pride. || But if it isn't, || _I'll see you in court. |||"},
]

SITUATIONS = {
  "perf": [
    "Complain to a hotel that your 'sea view' room faced a car park.",
    "Write to your neighbour about their cockerel, which starts at 4 a.m.",
    "Explain to your landlord why the kitchen ceiling is now purple.",
    "Complain to an airline that your suitcase went to Lisbon without you.",
    "Write to a restaurant about a 'small' portion that arrived on a spoon.",
    "Tell your boss why you arrived at the meeting dressed as a pirate.",
    "Write to the council about the pothole that swallowed your scooter.",
    "Complain to your sister that she gave away your secret recipe on TV.",
    "Write to a theme park about the 'gentle' ride that removed your eyebrows.",
    "Explain to a cinema why you should be refunded for falling asleep.",
    "Complain to a taxi company about a driver who sang opera the whole way.",
    "Tell a friend why you were banned from the village quiz night.",
    "Write to the gardening club about the giant marrow scandal.",
    "Complain to your phone company that autocorrect ruined your proposal.",
    "Explain to a museum why you were found inside the dinosaur.",
  ],
  "nat": [],
}

PLAN = {
  "routine": [
    ["2 min · warm-up", "lip trills, then 5 pitch sirens low to high, then 'red leather, yellow leather' crisp and fast"],
    ["5 min · Studio", "run the conductor once at today's speed, then record the script and read your numbers"],
    ["5 min · Sentence engine", "one frame, five different situations, all out loud"],
    ["5 min · Improv ring", "one round of 60 seconds, analysed"],
    ["3 min · Lexicon + log", "clear the due cards, then tick off the day"],
  ],
  "weeks": [
    {"title": "Ear and breath", "goal": "Hear the sprint-and-stop. Get your phrases fast and your pauses deliberate. Speed comes before melody.",
     "days": [
       {"focus": "listen", "tasks": ["Room 1: study the pace chart and all ten melodies", "Hum each melody shape twice", "Breath ladder up to 6"]},
       {"focus": "pace", "tasks": ["Studio: gym letter, conductor at 70%", "Record once, note your 'speed inside phrases'", "Technique: Sprint and stop"]},
       {"focus": "pauses", "tasks": ["Technique: A hierarchy of silences", "Mark a news paragraph with ‖ ‖‖ ‖‖‖ and perform it", "Record the gym letter again"]},
       {"focus": "fillers", "tasks": ["Technique: Restart on a marker", "Improv ring, conversation mode, 45 s, zero 'um'", "Breath ladder up to 8"]},
       {"focus": "pace", "tasks": ["Studio: hedge note at 85%", "Record and aim for silence 22–30%", "Lexicon: first cards"]},
       {"focus": "runs", "tasks": ["Technique: Breath for the long run", "Read the fastest grey-italic lines in one breath, 5 times", "Breath ladder up to 10"]},
       {"focus": "review", "tasks": ["Record the gym letter at 100%", "Compare with Day 2 in your log", "Rest your voice"]}]},
    {"title": "Melody", "goal": "Move your pitch. High on the setup, low on the punch, stretch the words you believe in.",
     "days": [
       {"focus": "range", "tasks": ["Technique: A baritone that moves", "10 sirens, then read the wedding letter with exaggerated ↗ and ↘", "Record: target range 14+ semitones"]},
       {"focus": "punch", "tasks": ["Technique: High setup, low punch", "Frame: Precise vagueness × 5", "Melody card: 'I can only describe as solid'"]},
       {"focus": "stretch", "tasks": ["Technique: Stretch instead of stall", "Frame: Deluded certainty × 5", "Studio: wedding letter at 85%"]},
       {"focus": "tone", "tasks": ["Technique: Wounded dignity", "Read a takeaway menu as a formal complaint, recorded", "Lexicon"]},
       {"focus": "fork", "tasks": ["Technique: The fork ending", "Frame: The fork ending × 5", "Studio: council appeal"]},
       {"focus": "conversation", "tasks": ["Room 1: compare stage vs conversation numbers", "Studio: first conversation script", "Record and check your range stays above 12"]},
       {"focus": "review", "tasks": ["Record the wedding letter at 100%", "Compare range and silence with week 1", "Rest"]}]},
    {"title": "Words and frames", "goal": "Load the frames and phrases until they come without thinking. This is what makes it flow in your head.",
     "days": [
       {"focus": "frames", "tasks": ["Sentence engine: Scene drop × 5", "Sentence engine: List with a turn × 5", "Lexicon"]},
       {"focus": "register", "tasks": ["Technique: Register collision", "Describe your commute using 4 mock-formal phrases", "Improv ring, stage, 60 s"]},
       {"focus": "frames", "tasks": ["Mock-intimate aside × 5", "Backhanded credit × 5", "Lexicon"]},
       {"focus": "conversation", "tasks": ["Technique: Think out loud, then land", "All conversation frames × 3 each", "Improv ring, conversation, 90 s"]},
       {"focus": "frames", "tasks": ["Charitable presumption × 5", "Undeterred restart × 5", "Studio: any script, at 100%"]},
       {"focus": "write", "tasks": ["Write your own 6-line complaint letter using 4 frames", "Mark it with the score notation", "Perform and record it"]},
       {"focus": "review", "tasks": ["Lexicon: clear everything due", "Improv ring × 2, one per mode", "Compare fillers/min with week 1"]}]},
    {"title": "Free flow", "goal": "No script. Real conversations and long improvisations. Use the coach's rewrites as your next take's target.",
     "days": [
       {"focus": "ring", "tasks": ["Improv ring, stage, 90 s × 2", "Ask the coach on the better one", "Redo using its rewrite"]},
       {"focus": "ring", "tasks": ["Improv ring, conversation, 2 min", "Tell a real story from your week in his conversational style", "Lexicon"]},
       {"focus": "real life", "tasks": ["Use 3 phrases in a real conversation today", "Tell one story to a friend with a ‖‖‖ after the payoff", "Log what happened"]},
       {"focus": "ring", "tasks": ["Coach writes a round × 2", "Record both, compare numbers", "Lexicon"]},
       {"focus": "mixed", "tasks": ["Answer 3 interview questions about yourself in conversation mode", "Then tell the same story in stage mode", "Notice how pace and range change"]},
       {"focus": "perform", "tasks": ["Perform your own complaint letter from Week 3, 100%", "Record and get coaching", "Second take with fixes"]},
       {"focus": "final", "tasks": ["Record the gym letter again and compare with Day 2", "Record a 2-minute improv and compare with Week 1", "Plan your next month: repeat Weeks 3–4"]}]},
  ],
}
